# Preparation
```{r}
library(tidyverse)
library(forcats) # need to load it separately
```

# Creating factors
```{r}
x1 <- c("Dec", "Apr", "Jan", "Mar")
x2 <- c("Dec", "Apr", "Jam", "Mar") # has a typo
# To create a factor you must start by creating a list of the valid levels:
month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", 
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
# now you can create a factor
y1 <- factor(x1, levels = month_levels)
y1
sort(y1)

# any values not in the set will be silently converted to NA
y2 <- factor(x2, levels = month_levels)
y2
# if you want a warning, you can use readr::parse_factor() function
y2 <- parse_factor(x2, levels = month_levels)

# if you omit the levels, they'll be taken from the data in alphabetical order
factor(x1)

# Sometimes you’d prefer that the order of the levels match the order of the first appearance in the data. You can do that when creating the factor by setting levels to unique(x), or after the fact, with fct_inorder():
f1 <- factor(x1, levels = unique(x1))
f1

f2 <- x1 %>% factor() %>% fct_inorder()
f2

# if you need to access the set of valid levels
levels(f2)
```

# General social survey
```{r}
gss_cat

# when factors are stored in a tibble, you can't see their levels so easily. you can use count()
gss_cat %>% 
  count(race)
# or with a bar chart
ggplot(gss_cat, aes(race)) +
  geom_bar() # by default, ggplot2 will drop levels that don't have any values. you can force them to display
ggplot(gss_cat, aes(race)) +
  geom_bar() +
  scale_x_discrete(drop = FALSE)
```

# Exercise
```{r}
# 1. Explore the distribution of rincome (reported income). What makes the default bar chart hard to understand? How could you improve the plot?
gss_cat %>% count(rincome)
ggplot(gss_cat, aes(rincome)) +
  geom_bar() # it's hard to read the default bar chart because the label of each level is overlap with each other; we can flip the coordinates
ggplot(gss_cat, aes(rincome)) +
  geom_bar() +
  coord_flip()

# 2. What is the most common relig in this survey? What’s the most common partyid?
gss_cat %>% count(relig) %>% arrange(desc(n)) # Protestant is the most common religion
gss_cat %>% count(partyid) %>% arrange(desc(n)) # Independent is the most common party

# 3. Which relig does denom (denomination) apply to? How can you find out with a table? How can you find out with a visualisation?
gss_cat %>% group_by(relig) %>% count(denom) # denom applies to Protestant
ggplot(gss_cat, aes(x = relig, color = denom)) +
  geom_bar() +
  coord_flip()
```

# Modifying factor order
```{r}
relig_summary <-gss_cat %>% 
  group_by(relig) %>% 
  summarise(tvhours = mean(tvhours, na.rm = TRUE), 
            age = mean(age, na.rm = TRUE),
            n = n())
ggplot(relig_summary, aes(tvhours, relig)) + geom_point()
# use fct_reorder() to reorder the levels
ggplot(relig_summary, aes(tvhours, fct_reorder(relig, tvhours))) + geom_point()

# create a similar plot looking at how average age varies across reported income level
gss_cat %>% 
  group_by(rincome) %>% 
  summarise(age = mean(age, na.rm = TRUE)) %>% 
  ggplot(aes(age, fct_reorder(rincome, age))) +
  geom_point()
# here reordering the levels isn't a good idea because rincome already has a principled order that we shouldn't mess with. Reserve fct_reorder() for factors whose levels are arbitrarily ordered. you can use fct_relevel(). It takes a factor, f, and then any number of levels that you want to move to the front of the line.
gss_cat %>% 
  group_by(rincome) %>% 
  summarise(age = mean(age, na.rm = TRUE)) %>% 
  ggplot(aes(age, fct_relevel(rincome, "Not applicable"))) +
  geom_point()

# Another type of reordering is useful when you are colouring the lines on a plot. fct_reorder2() reorders the factor by the y values associated with the largest x values. This makes the plot easier to read because the line colours line up with the legend.
by_age <- gss_cat %>% 
  filter(!is.na(age)) %>% 
  group_by(age, marital) %>%
  count() %>% 
  mutate(prop = prop.table(n))
ggplot(by_age, aes(age, prop, colour = marital)) +
  geom_line(na.rm = TRUE)
ggplot(by_age, aes(age, prop, colour = fct_reorder2(marital, age, prop))) +
  geom_line() + 
  labs(colour = "marital")

# for bar plots, you can use fct_infreq() to order levels in increasing frequency. you may combine with fct_rev()
gss_cat %>% 
  mutate(marital = marital %>% fct_infreq() %>% fct_rev()) %>% 
  ggplot(aes(marital)) +
  geom_bar()
```

# Exercise
```{r}
# 1. There are some suspiciously high numbers in tvhours. Is the mean a good summary?
# there might be some data entry errors regarding the number of hours spent in watching TV. it's not very believable that someone spent 20-24 hours watching tv each day. 
gss_cat %>% filter(!is.na(tvhours)) %>% ggplot(aes(tvhours)) + geom_histogram(binwidth = 1)

# 2. For each factor in gss_cat identify whether the order of the levels is arbitrary or principled.
levels(gss_cat$marital) # arbitrary
levels(gss_cat$race) 
gss_cat %>%
  ggplot(aes(race)) +
  geom_bar(drop = FALSE) # principled by the number of people in each category

levels(gss_cat$rincome) # principled
levels(gss_cat$relig) # arbitrary
levels(gss_cat$partyid) # principled
levels(gss_cat$denom) # principled

# 3. Why did moving “Not applicable” to the front of the levels move it to the bottom of the plot?
```

# Modifying factor levels
```{r}
# fct_recode() allows you to recode, or change, the value of each level. it will leave levels that aren't explicitly mentioned as is. the formula is NEW name=OLD name
gss_cat %>% count(partyid)
gss_cat %>% 
  mutate(partyid = fct_recode(partyid,
    "Republican, strong"    = "Strong republican",
    "Republican, weak"      = "Not str republican",
    "Independent, near rep" = "Ind,near rep",
    "Independent, near dem" = "Ind,near dem",
    "Democrat, weak"        = "Not str democrat",
    "Democrat, strong"      = "Strong democrat")) %>% 
  count(partyid)

# to combine groups, you can assign multiple old levels to the same new level
gss_cat %>%
  mutate(partyid = fct_recode(partyid,
    "Republican, strong"    = "Strong republican",
    "Republican, weak"      = "Not str republican",
    "Independent, near rep" = "Ind,near rep",
    "Independent, near dem" = "Ind,near dem",
    "Democrat, weak"        = "Not str democrat",
    "Democrat, strong"      = "Strong democrat",
    "Other"                 = "No answer",
    "Other"                 = "Don't know",
    "Other"                 = "Other party"
  )) %>%
  count(partyid)

# If you want to collapse a lot of levels, fct_collapse() is a useful variant of fct_recode(). 
gss_cat %>%
  mutate(partyid = fct_collapse(partyid,
    other = c("No answer", "Don't know", "Other party"),
    rep = c("Strong republican", "Not str republican"),
    ind = c("Ind,near rep", "Independent", "Ind,near dem"),
    dem = c("Not str democrat", "Strong democrat")
  )) %>%
  count(partyid)

# sometimes you just want to lump together all the small groups to make a plot or table simpler. Use fct_lump(). Lump together least/most common factor levels into "other"
gss_cat %>%
  mutate(relig = fct_lump(relig)) %>%
  count(relig)
# we can use the n parameter to specify how many groups (excluding other) we want to keep:
gss_cat %>%
  mutate(relig = fct_lump(relig, n = 10)) %>%
  count(relig, sort = TRUE) %>%
  print(n = Inf)
```

# Exercise
```{r}
# 1. How have the proportions of people identifying as Democrat, Republican, and Independent changed over time?
gss_cat %>% count(partyid)
gss_cat %>% 
  mutate(partyid = fct_collapse(partyid,
          "Democrat" = c("Not str democrat", "Strong democrat"),
          "Republican" = c("Strong republican", "Not str republican"),
          "Independent" = c("Ind,near dem", "Ind,near rep", "Independent"),
          "Other" = c("No answer", "Don't know", "Other party"))) %>% 
  group_by(year) %>% 
  count(partyid) %>% 
  mutate(prop = prop.table(n)) %>% 
  ggplot(aes(x = year, y = prop, color = fct_reorder2(partyid, year, prop))) +
  geom_point() + 
  labs(colour = "Party Id.")

# 2. How could you collapse rincome into a small set of categories?
gss_cat %>% count(rincome)
gss_cat %>% 
  mutate(rincome = fct_collapse(rincome, 
                    "Unknown" = c("No answer", "Don't know", "Refused", "Not applicable"),
                    "LT $5,000" = c("Lt $1000", "$1000 to 2999", "$3000 to 3999", "$4000 to 4999"),
                    "GT $5,000, LT $10,000" = c("$5000 to 5999", "$6000 to 6999", "$7000 to 7999", "$8000 to 9999"),
                    "GT $10,000" = c("$10000 - 14999", "$15000 - 19999", "$20000 - 24999", "$25000 or more"))) %>% 
  ggplot(aes(x = rincome)) +
  geom_bar() +
  coord_flip()
```
