# Preparation
```{r}
library(tidyverse)
library(lubridate)
library(nycflights13)
```

# Creating date/times
```{r}
today() #get the current date
now() #get the current date-time
```

# Creating date/times from strings
```{r}
ymd("2017-01-31") # the order needs to be same with the string
mdy("Jan. 31, 2018") # the comma is optional. you can use full spelling or abbreviated term
dmy("31Jan2017") # the way you present the string doesn't matter that much. you can have space between each word or not.
ymd(170131) # it also takes an unquoted numbers. the year can be four digits or two. the month and day need to be two digits

# to create a date-time, add an underscore and one or more of "h", "m", and "s"
ymd_hms("17-1-1 20:11:19") # need a space between date and time. if there is a separator, month and day don't need to be two digits. it doesn't take an unquoted numbers
mdy_hm("01/31/17 8:1")

# by supplying a time zone, you force the creation of a date-time from a date
ymd(20170131, tz = "UTC")
```

# Creating date/times from individual components
```{r}
# use make_date() for dates, or make_datetime() for date-times
flights %>% 
  select(year, month, day, hour, minute) %>% 
  mutate(departure = make_datetime(year, month, day, hour, minute))

make_datetime_100 <- function(year, month, day, time){
  make_datetime(year, month, day, time %/% 100, time %% 100)
}
flights_dt <- flights %>% 
  filter(!is.na(dep_time), !is.na(arr_time)) %>% 
  mutate(
    dep_time = make_datetime_100(year, month, day, dep_time),
    arr_time = make_datetime_100(year, month, day, arr_time),
    sched_dep_time = make_datetime_100(year, month, day, sched_dep_time),
    sched_arr_time = make_datetime_100(year, month, day, sched_arr_time)
  ) %>% 
  select(origin, dest, ends_with("delay"), ends_with("time"))
flights_dt

# visualize the distribution of departure times across the year
flights_dt %>% 
  ggplot(aes(dep_time)) +
  geom_freqpoly(binwidth = 86400) # # 86400 seconds = 1 day

# within a single day
flights_dt %>% 
  filter(dep_time < ymd(20130102)) %>% 
  ggplot(aes(dep_time)) +
  geom_freqpoly(binwidth = 600) # 600 seconds = 10 mins
```

# Creating date/times from other types
```{r}
# use as_datetime() and as_date() to switch between a date-time and a date.
as_datetime(today())
as_date(now())

# Sometimes you’ll get date/times as numeric offsets from the “Unix Epoch”, 1970-01-01. If the offset is in seconds, use as_datetime(); if it’s in days, use as_date().
as_datetime(60*60*10)
as_date(365*10+2)
```

# Exercise
```{r}
# 1. What happens if you parse a string that contains invalid dates?
ymd(c("2010-10-10", "bananas")) # it will throw a warning saying one string failed to parse. it will give NA

# 2. What does the tzone argument to today() do? Why is it important?
today(tzone = "EST")
today(tzone = "GMT") # tzone argument finds the current date in that time zone

# 3. Use the appropriate lubridate function to parse each of the following dates:
d1 <- "January 1, 2010"
mdy(d1)

d2 <- "2015-Mar-07"
ymd(d2)

d3 <- "06-Jun-2017"
dmy(d3)

d4 <- c("August 19 (2015)", "July 1 (2015)")
mdy(d4)

d5 <- "12/30/14" # Dec 30, 2014
mdy(d5)
```

# Date-time components 
```{r}
# Getting components
datetime <- ymd_hms("2016-07-08 12:34:56")
year(datetime); month(datetime); day(datetime)
mday(datetime); yday(datetime); wday(datetime)
# For month() and wday() you can set label = TRUE to return the abbreviated name of the month or day of the week. Set abbr = FALSE to return the full name.
month(datetime, label = TRUE)
month(datetime, label = TRUE, abbr = FALSE)
wday(datetime, label = TRUE, abbr = FALSE)

flights_dt %>% 
  mutate(wday = wday(dep_time, label = TRUE)) %>% 
  ggplot(aes(x = wday)) + 
  geom_bar() # more flights depart during the week than on the weekend

flights_dt %>%
  mutate(minute = minute(dep_time)) %>% 
  group_by(minute) %>% 
  summarise(
    ave_delay = mean(arr_delay, na.rm = TRUE),
    n = n()) %>% 
  ggplot(aes(x = minute, y = ave_delay)) +
  geom_line() # flights depart within 20-30 mins in a hour or within 50-60 mins in a hour have much less delay

sched_dep <- flights_dt %>%
  mutate(minute = minute(sched_dep_time)) %>% 
  group_by(minute) %>% 
  summarise(
    ave_delay = mean(arr_delay, na.rm = TRUE),
    n = n()) 
sched_dep %>% 
  ggplot(aes(x = minute, y = ave_delay)) +
  geom_line()

ggplot(sched_dep, aes(minute, n)) + 
  geom_line()

# Rounding
flights_dt %>% 
  count(week = floor_date(dep_time, "week")) %>% 
  ggplot(aes(week, n)) +
    geom_line() # plot the number of flights per week

# Setting components
(datetime <- ymd_hms("2016-07-08 12:34:56"))

year(datetime) <- 2020
datetime

month(datetime) <- 01
datetime

hour(datetime) <- hour(datetime) + 1
datetime
# Alternatively, rather than modifying in place, you can create a new date-time with update(). This also allows you to set multiple values at once.
update(datetime, year = 2020, month = 2, mday = 2, hour = 2)
# if values are too big, they'll roll over
ymd("2015-02-1") %>% 
  update(mday = 30)
ymd("2015-02-01") %>% 
  update(hour = 400)

# You can use update() to show the distribution of flights across the course of the day for every day of the year
flights_dt %>% 
  mutate(dep_hour = update(dep_time, yday = 1)) %>% 
  ggplot(aes(dep_hour)) +
    geom_freqpoly(binwidth = 300)
```

# Exercise
```{r}
# 1. How does the distribution of flight times within a day change over the course of the year?
flights_dt %>% 
  mutate(time = hour(dep_time) * 100 + minute(dep_time),
         day = day(floor_date(dep_time, "day")),
         month = as.factor(month(dep_time))) %>% 
  ggplot(aes(x= time, y = ..density.., color = month)) +
  geom_freqpoly(binwidth = 100)

# 2. Compare dep_time, sched_dep_time and dep_delay. Are they consistent? Explain your findings.
flights_dt %>% 
  mutate(dif = (dep_time - sched_dep_time)/60,
         dif = str_sub(dif, start = -6),
         check = ifelse(dif == dep_delay, 1, 0)) %>% 
  arrange(check) %>% 
  count(check)
# they are not consistent. some of the dep_time were recorded incorrectly. for example, "2013-01-03 00:32:00", should have been recorded as "2013-01-04 00:32:00".

# 3. Compare air_time with the duration between the departure and arrival. Explain your findings. (Hint: consider the location of the airport.)
flights_dt %>% 
  mutate(dif = as.numeric(arr_time - dep_time)) # the time differences between arrival and departure times don't match the air_time

# 4. How does the average delay time change over the course of a day? Should you use dep_time or sched_dep_time? Why?
flights_dt %>% 
  mutate(hour = hour(sched_dep_time)) %>% 
  group_by(hour) %>% 
  summarise(ave = mean(dep_delay, na.rm = TRUE)) %>% 
  ggplot(aes(x = hour, y = ave)) +
  geom_point() +
  geom_smooth()

# 5. On what day of the week should you leave if you want to minimise the chance of a delay?
flights_dt %>% 
  mutate(wday = wday(dep_time)) %>% 
  filter(dep_delay > 0) %>% 
  group_by(wday) %>% 
  summarise(delay = mean(dep_delay, na.rm = TRUE)) %>% 
  ggplot(aes(x = wday, y = delay)) +
  geom_point() +
  geom_smooth() # Sunday has the lowest departure delay

# 6. What makes the distribution of diamonds$carat and flights$sched_dep_time similar?
diamonds %>% 
  ggplot(aes(x = carat)) +
  geom_histogram(binwidth = 0.01)
flights %>% 
  ggplot(aes(x = sched_dep_time)) +
  geom_histogram(binwidth = 10)

# 7. Confirm my hypothesis that the early departures of flights in minutes 20-30 and 50-60 are caused by scheduled flights that leave early. Hint: create a binary variable that tells you whether or not a flight was delayed.
flights_dt %>% 
  mutate(delay = ifelse(dep_delay > 0, 1, 0),
         min = minute(dep_time)) %>%
  filter((min >= 20 & min <= 30 | min >= 50 & min <= 60) & delay == 0) %>% 
  mutate(dif = as.numeric(sched_dep_time - dep_time),
         pn = ifelse(dif > 0, 1, ifelse(dif < 0, 2, ifelse(dif == 0, 3, 4)))) %>% 
  count(pn)
# the result showed that 7036 records whose scheduled departure time is same with the actual departure time. the rest of cases whose scheduled departure time is later than the actual departure time.
```

# Time spans: Durations
```{r}
h_age <- today() - ymd(19791014)
h_age
as.duration(h_age)

dseconds(15) # durations come with a bunch of convenient constructors. they always record the time span in seconds. doesn't have dmonths function
dminutes(10)
dhours(c(12,24))
ddays(0:5)
dweeks(3)
dyears(1)

2 * dyears(1)
dyears(1) + dweeks(12) + dhours(15)

tomorrow <- today() + ddays(1)
last_year <- today() - dyears(1)

# because durations represent an exact number of seconds, sometimes you might get an unexpected result:
one_pm <- ymd_hms("2016-03-12 13:00:00", tz = "America/New_York")
one_pm
one_pm + ddays(1) # the result show 2pm on 3/13 because of the DST. that's the day the Daylight saving time kicks in
```

# Periods
```{r}
# to solve the above problem, we can use periods. Periods are time spans but don’t have a fixed length in seconds, instead they work with “human” times, like days and months. 
one_pm + days(1)

# Periods have a bunch of convenient constructors; it has months() function
seconds(15)
minutes(10)
hours(c(12,24))
days(0:5)
weeks(3)
months(1:6)
years(1)

10 * (months(10) + days(1))
days(50) + hours(25) + minutes(2)

ymd("2016-01-01") + dyears(1) # this is a leap year
ymd("2016-01-01") + years(1)

one_pm + ddays(1) # daylight saving time
one_pm + days(1)

# Good way to create binary variables!!!
flights_dt <- flights_dt %>%   
  mutate(overnight = arr_time < dep_time, # gives TRUE or FALSE
         arr_time = arr_time + days(overnight * 1),
         sched_arr_time = sched_arr_time + days(overnight * 1))
flights_dt %>% 
  filter(overnight, arr_time < dep_time) # now all of the flights have later arrival time than the departure time.
```

# Intervals
```{r}
# an interval is a duration with a starting point: that makes it precise so you can determine exactly how long it is
next_year <- today() + years(1)
(today() %--% next_year)/ddays(1) # "%--%" creates an interval, the starting point is on the left and the ending point is on the right
(today() %--% next_year)%/%ddays(1) # to find out how many periods fall into an interval
```

# Exercise
```{r}
# 1. Why is there months() but no dmonths()?
# different months have differnt days and thus have different seconds. duration gives exact seconds, so duration can't give exact seconds contained in a month.

# 2. Explain days(overnight * 1) to someone who has just started learning R. How does it work?
# when overnight == TRUE, it will be 1*1; when overnight == FALSE, it will be 0*1

# 3. Create a vector of dates giving the first day of every month in 2015. Create a vector of dates giving the first day of every month in the current year.
month <- c(1:12)
day <- 1
date <- function(year){
  make_date(year, month, day)
}
date(2015); date(2018)

# 4. Write a function that given your birthday (as a date), returns how old you are in years.
interval <- function(year, month, day){
  birthday <- make_date(year, month, day)
  (birthday %--% today()) %/% years(1)
}

# 5. Why can’t (today() %--% (today() + years(1)) / months(1) work? Because it lacks a closing ")"
(today() %--% (today() + years(1))) / months(1)
```

# Time zones
```{r}
Sys.timezone() # what R thinks my time zone is
length(OlsonNames()) # see the complete list of all time zone names
head(OlsonNames())

(x1 <- ymd_hms("2015-06-01 12:00:00", tz = "America/New_York"))
(x2 <- ymd_hms("2015-06-01 18:00:00", tz = "Europe/Copenhagen"))
(x3 <- ymd_hms("2015-06-02 04:00:00", tz = "Pacific/Auckland"))
x1-x2; x1-x3

x4 <- c(x1,x2,x3) # operation like c(), will often drop the time zone. In that case, the date-times will display in your local time zone:
x4

# change the time zone; Keep the instant in time the same, and change how it’s displayed. Use this when the instant is correct, but you want a more natural display.
x4a <- with_tz(x4, tzone = "Australia/Lord_Howe")
x4a
x4a-x4

# Change the underlying instant in time. Use this when you have an instant that has been labelled with the incorrect time zone, and you need to fix it.
x4b <- force_tz(x4, tzone = "Australia/Lord_Howe")
x4b
x4b-x4
```