---
title: "Covariation"
author: "Xin Y. Gao"
date: "January 24, 2018"
output: html_document
---

# a categorical and continuous variables: use histogram, freqpoly, boxplot
```{r}
ggplot(data = diamonds, mapping = aes(x = price, y = ..density..)) +
        geom_freqpoly(mapping = aes(color = cut), binwidth = 500) # plot density
ggplot(data = diamonds, mapping = aes(x = cut, y = price)) +
        geom_boxplot()
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
        geom_boxplot() # to make the trend easier to read, we can reorder class based on the median value of hwy
ggplot(data = mpg, mapping = aes(x = reorder(class, hwy, FUN = median), y = hwy)) +
        geom_boxplot() # reorder class variable
ggplot(data = mpg, mapping = aes(x = reorder(class, hwy, FUN = median), y = hwy)) +
        geom_boxplot() +
        coord_flip()
```

# Exercises
```{r}
# 1. departure times of cancelled and non-cancelled flights (should use density plot instead of count
# because counts for the cancelled flights are much lower than the non-cancelled flights)
flights %>% 
        mutate(cancel = is.na(dep_time),
               deptime = sched_dep_time %/% 100 + sched_dep_time %% 100/60) %>% 
        select(sched_dep_time,dep_time, cancel, deptime) %>% 
        ggplot(mapping = aes(x = deptime, y = ..density..)) +
        geom_freqpoly(mapping = aes(color = cancel), binwidth = 0.5)

# 2. carat should be the most important variable for predicting the price.
diamonds %>%
        ggplot(mapping = aes(x = carat, y = ..density..)) +
        geom_freqpoly(mapping = aes(color = cut), binwidth = 0.1)
# diamonds in good cut tend to have lower carat values, but diamonds with lower quality tend to have big carat values. 

# 3. install the ggstance package and create a horizontal boxplot. how does this compare to using coord_flip()?
library(ggstance)
ggplot(mpg, aes(x = reorder(class, hwy, FUN = median), y = hwy)) +
        geom_boxplot() +
        coord_flip()
ggplot(mpg, aes(x = hwy, y = reorder(class, hwy, FUN = median))) +
        geom_boxploth()
# the above two codes give the same plot. when using geom_boxplot(), categorical variable is on the x axis,
# continuous variable is on the y axis. when using geom_boxploth(), categorical variable is on the y axis and 
# continuous variable is on the x axis.

# 4. the boxplots tend to display a large number of "outlying values". one remedy is to use the 
# geom_lv() in the lvplot package.
library(lvplot)
ggplot(diamonds, aes(x = cut, y = price)) +
  geom_lv() # geom_lv() reduces the number of outliers

# 5. compare and contrast geom_violin() with a facet geom_histogram() or a colored geom_freqploy(), what' the pros and cons
ggplot(diamonds, aes(price, ..density..)) +
  geom_freqpoly(aes(color = cut), binwidth = 500)
ggplot(diamonds, aes(price)) +
  geom_histogram(binwidth = 500) +
  facet_wrap(~ cut, ncol = 1, scales = "free_y")
ggplot(diamonds, aes(cut, price)) +
  geom_violin() +
  coord_flip()

# 6. if you have a small dataset, sometimes it's useful to use geom_jitter() to see the relationship between a continuous and categorical variable.
library(ggbeeswarm)
```

# Two categorical variables
```{r}
# to visualize the covariation between categorical variables, you'll need to count the number of observations for each combination. you can use geom_count()
ggplot(data = diamonds) +
  geom_count(mapping = aes(x = cut, y = color))

# you can also compute the count using dplyr, then visualize with geom_tile()
diamonds %>% 
  count(cut, color) %>% 
  ggplot(mapping = aes(x= color, y = cut)) +
  geom_tile(mapping = aes(fill = n))
```

# Exercise
```{r}
# 1. how could you rescale the count dataset above to more clearly show the distribution of cut within color or color within cut?
diamonds %>% 
  count(color, cut) %>% 
  group_by(color) %>% 
  mutate(prop = n / sum(n)) %>% 
  ggplot(aes(x = color, y = cut)) +
  geom_tile(mapping = aes(fill = prop)) +
  scale_fill_viridis_c(limits = c(0,1))
diamonds %>% 
  count(color, cut) %>% 
  group_by(cut) %>% 
  mutate(prop = n / sum(n)) %>% 
  ggplot(aes(x = color, y = cut)) +
  geom_tile(mapping = aes(fill = prop)) +
  scale_fill_viridis_c(limits = c(0,1))

# 2. use geom_tile() together with dplyr to explore how average flight delays vary by destination and month of year. 
flights %>% 
  filter(!is.na(dep_time)) %>% 
  group_by(dest, year, month) %>% 
  mutate(ave = sum(dep_delay) / n()) %>% 
  select(dest, year, month, ave) %>% 
  ggplot(aes(factor(month), dest)) +
  geom_tile(aes(fill = ave))
# improved version
flights %>% 
  filter(!is.na(dep_time)) %>% 
  group_by(dest, year, month) %>% 
  summarise(average_delay = mean(dep_delay)) %>% 
  group_by(dest) %>% 
  filter(n() == 12) %>% 
  ungroup() %>% 
  mutate(destination = fct_reorder(dest, average_delay)) %>% 
  ggplot(aes(x = factor(month), y = destination)) +
  geom_tile(aes(fill = average_delay)) +
  scale_fill_viridis_c()

# 3. why is it slightly better to use aes(x=color, y=cut) rather than aes(x= cut, y=color) in the example above?
# It's usually better to use the categorical variable with a larger number of categories or the longer labels on the y axis. 
```

# Two continuous variables
```{r}
# geom_point() can be challenging when deal with a lot of data. alpha can be used to aleviate this
ggplot(data = diamonds) +
  geom_point(aes(x = carat, y = price), alpha = 1/100)

# use geom_bin2d() and geom_hex() to bin in two dimensions. geom_bin2d() and geom_hex() divide the coordinate plane into 2d bins and then use a fill color to display how many points fall into each bin
ggplot(data = diamonds) +
  geom_bin2d(mapping = aes(x = carat, y = price))

library(hexbin)
ggplot(data = diamonds) +
  geom_hex(mapping = aes(x = carat, y = price))

# you can bin one continuous variable, so it acts like a categorical variable.
ggplot(data = diamonds, mapping = aes(x = carat, y = price)) +
  geom_boxplot(aes(group = cut_width(carat, 0.1)))

ggplot(data = diamonds, mapping = aes(x = carat, y = price)) +
  geom_boxplot(aes(group = cut_width(carat, 0.1)), varwidth = TRUE) # make the width of the boxplot proportional to the number of points

ggplot(data = diamonds, mapping = aes(x = carat, y = price)) +
  geom_boxplot(aes(group = cut_number(carat, 20))) # display approximately the same number of points in each bin
```

# Exercise
```{r}
# 1. 
```